--------INSERCCIÓN DE DATOS-------- 
--HABITACIONES--
INSERT INTO HABITACIONES
VALUES (1,1,2);
INSERT INTO HABITACIONES
VALUES (2,2,2);
INSERT INTO HABITACIONES
VALUES (3,3,2);
INSERT INTO HABITACIONES
VALUES (4,4,2);
INSERT INTO HABITACIONES
VALUES (5,5,2);

--MEDICOS--
INSERT INTO MEDICOS
VALUES (1,'JUAN','PEREZ FRANCIA','jperezfrancia@servet.com','12345678J');
INSERT INTO MEDICOS
VALUES (2,'MARCOS','LOPEZ ALONSO','mlopezalonso@servet.com','87654321M');
INSERT INTO MEDICOS
VALUES (3,'ALBERTO','RUIZ SAENZ','aruizsanez@servet.com','43215678A');
INSERT INTO MEDICOS
VALUES (4,'IVAN','FERNANDEZ SOTO','ifernandezsoto@servet.com','56784321I');
INSERT INTO MEDICOS
VALUES (5,'MARIA ','ALVAREZ TORRES','malvareztorres@servet.com','87563421M');

--PACIENTES-- 
INSERT INTO PACIENTES
VALUES (1,'LUIS','GASCA MARTIN','12435687L');
INSERT INTO PACIENTES
VALUES (2,'RAQUEL','RODRIGUEZ LIZARTE','65457832R');
INSERT INTO PACIENTES
VALUES (3,'FRAN','ORTIZ ZUERAS','83917265F');
INSERT INTO PACIENTES
VALUES (4,'ELENA','MARTINEZ DELGADO','91827364E');
INSERT INTO PACIENTES
VALUES (5,'LUCIA','GARCIA FORNAS','56747438K');

--INGRESOS--
INSERT INTO INGRESOS
VALUES (1,'26/01/2020',3,1,2);
INSERT INTO INGRESOS
VALUES (2,'04/08/2014',1,4,3);
INSERT INTO INGRESOS 
VALUES (3,'30/01/2018',5,2,5);
INSERT INTO INGRESOS 
VALUES (4,'17/10/2018',2,3,1);
INSERT INTO INGRESOS
VALUES (5,'20/04/2015',4,5,4);
UPDATE INGRESOS 
    SET FECHA_SALIDA='28/01/2020'
    WHERE ID_PACIENTE=1;
UPDATE INGRESOS 
    SET FECHA_SALIDA='10/08/2014'
    WHERE ID_PACIENTE=2;
UPDATE INGRESOS 
    SET FECHA_SALIDA='12/02/2018'
    WHERE ID_PACIENTE=3;
UPDATE INGRESOS 
    SET FECHA_SALIDA='17/10/2018'
    WHERE ID_PACIENTE=4;
UPDATE INGRESOS 
    SET FECHA_SALIDA='28/05/2015'
    WHERE ID_PACIENTE=5;
SELECT *FROM INGRESOS;

--ESPECIALIDADES--
INSERT INTO ESPECIALIDADES
VALUES (1,'TRAUMATOLOGÍA',5,'SANTIAGO GIL OLIVEIRA');
INSERT INTO ESPECIALIDADES
VALUES (2,'NEUROLOGÍA',3,'NEREA ALVAREZ RODRIGUEZ');
INSERT INTO ESPECIALIDADES
VALUES (3,'GINECOLOGÍA',4,'OSCAR SUAREZ PEREZ');
INSERT INTO ESPECIALIDADES
VALUES (4,'UROLOGÍA',1,'AHINOA GONZALEZ NEILA');
INSERT INTO ESPECIALIDADES
VALUES (5,'CARDIOLOGÍA',2,'LARA ALONSO LOZANO');



